authentication:
  secret-key: rvsf2Zk4adpAJ41rIesA4g==
  expiration-time: 864000000 # 1 day

encryption:
  secret-key: RB15AW0JUI7ZL8BX

server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    database: mysql

  kafka:
    bootstrap-servers: kafka:9092
    template:
      email-direct: email-direct
      email-schedule: email-schedule
    consumer:
      bootstrap-servers: kafka:9092
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.transaction: TRACE