spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true

authentication:
  secret-key: rvsf2Zk4adpAJ41rIesA4g==
  expiration-time: 864000000 # 1 day